server:
    port: 9196

tenants:
  datasources:
    tenant1:
      jdbcUrl: jdbc:mysql://localhost:3306/patientDb1?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: ${username}
      password: ${password}
    tenant2:
      jdbcUrl: jdbc:mysql://localhost:3306/patientDb2?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: ${username}
      password: ${password}
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
